# Generated by Django 4.2.7 on 2023-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_receptionist_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('to_meet', models.CharField(max_length=50)),
                ('date_of_visit', models.DateField()),
            ],
        ),
    ]
