# Generated by Django 4.2.7 on 2023-12-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='password',
            field=models.CharField(default='12345', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.IntegerField(choices=[(1, 'Business Visit'), (2, 'Personal Visit'), (3, 'Job Visit'), (4, 'Others')]),
        ),
    ]
