# Generated by Django 4.2.7 on 2023-12-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_receptionist_password_alter_visitor_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
    ]
