# Generated by Django 4.2.7 on 2023-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_visitreason_alter_visitor_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='role',
        ),
        migrations.AddField(
            model_name='receptionist',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='state',
            field=models.CharField(default='', max_length=150),
        ),
    ]
