# Generated by Django 4.2.7 on 2023-12-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_remove_receptionist_role_receptionist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
