# Generated by Django 4.2.7 on 2023-12-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_receptionist_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='createdBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='last_updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='who_updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='createdBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='who_updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
